// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import fs from 'fs';
import path from 'path';
import { StateMachine, StateMachineProps } from '@matthewbonig/state-machine';
import { Construct } from 'constructs';
export interface SampleStateMachineOverrides {
  readonly 'Execute function': Partial<{
    'Type': string;
    'Resource': string;
    'OutputPath': string;
    'Parameters': Partial<{
      'FunctionName': string;
      'Payload.$': string;
    }>;
    'End': Partial<{
    }>;
  }>;
}
export interface SampleStateMachineProps extends Omit<StateMachineProps, 'overrides' | 'definition'> {
  readonly overrides: Partial<SampleStateMachineOverrides>;
}
export class SampleStateMachine extends StateMachine {
  constructor(scope: Construct, id: string, props: SampleStateMachineProps) {
    super(scope, id, {
      ...props,
      definition: JSON.parse(fs.readFileSync(path.join(__dirname, 'sample.workflow.json')).toString()),
    });
  }
}